### ISSUE TITLE
npm update

### ISSUE THREAD

**Issue by bobrik** [sourcemint/util-js#6]
This module depends on http url instead of package name in npm. You probably should update version and do `npm publish` to fix that.

That's very annoying when you live in closed network where you can only talk to npm.

**Comment by cadorn** [comment]
I don't follow.

**Comment by bobrik** [comment]
bobrik@air-2 /tmp % npm install sourcemint-util-js
npm http GET https://registry.npmjs.org/sourcemint-util-js
npm http 304 https://registry.npmjs.org/sourcemint-util-js
npm http GET https://registry.npmjs.org/wrench/1.3.9
**npm http GET https://github.com/LearnBoost/console-trace/tarball/8a54bf706d001f1eef166b99391e952e4be10982**
npm http GET https://registry.npmjs.org/n-util/0.0.1
npm http GET https://registry.npmjs.org/q/0.8.5
npm http GET https://registry.npmjs.org/glob/3.1.12
npm http 304 https://registry.npmjs.org/wrench/1.3.9
npm http 304 https://registry.npmjs.org/q/0.8.5
npm http 304 https://registry.npmjs.org/glob/3.1.12
npm http 304 https://registry.npmjs.org/n-util/0.0.1
**npm http 200 https://github.com/LearnBoost/console-trace/tarball/8a54bf706d001f1eef166b99391e952e4be10982**
npm http GET https://registry.npmjs.org/callsite/0.0.2
npm http GET https://registry.npmjs.org/inherits/1.0.0
npm http GET https://registry.npmjs.org/minimatch/0.2.6
npm http GET https://registry.npmjs.org/graceful-fs/1.1.10
npm http 304 https://registry.npmjs.org/callsite/0.0.2
npm http 304 https://registry.npmjs.org/minimatch/0.2.6
npm http 304 https://registry.npmjs.org/inherits/1.0.0
npm http 304 https://registry.npmjs.org/graceful-fs/1.1.10
npm http GET https://registry.npmjs.org/lru-cache/2.0.1
npm http 200 https://registry.npmjs.org/lru-cache/2.0.1
npm http GET https://registry.npmjs.org/lru-cache/-/lru-cache-2.0.1.tgz
npm http 200 https://registry.npmjs.org/lru-cache/-/lru-cache-2.0.1.tgz
sourcemint-util-js@0.1.53 node_modules/sourcemint-util-js
├── wrench@1.3.9
├── n-util@0.0.1
├── q@0.8.5
├── console-trace@0.1.0 (callsite@0.0.2)
└── glob@3.1.12 (inherits@1.0.0, graceful-fs@1.1.10, minimatch@0.2.6)

Bold lines are github urls, not npm. Everything should be in npm.

**Comment by cadorn** [comment]
Ah, right. Of course. That console-trace commit has since made it onto NPM. Will be fixed as part of sm@0.3.0 to be released this or next week.
